# Otras estadísticas

La prueba de Kuiper esta muy relacionada con la prueba Kolmogorov–Smirnov (o prueba K-S). Como la prueba $K-S$, esta prueba utiliza las estadísticas $D^+$ y $D^-$ que representan las diferencias más positivas y más negativas entre las distribuciones que se están comparando. La estadística de prueba de Kuiper es:
$$V=D^+ + D^-.$$
Con este pequeño cambio, la prueba de Kuiper es tan sensible en las colas como lo es en la mediana de la distribución.

Las pruebas **Anderson–Darling** y **Cramér–von Mises** pertenecen a un grupo llamado **estadísticas EDF cuadráticas**, en donde el término EDF se refiere a que se basan en la función de distribución empírica. 

Este grupo de estadísticas está definido de la siguiente manera:
$$n\int_{-\infty}^{\infty}(S(x)-F_0(x))^2w(x)dF_0(x).$$
En donde la diferencia entre la distribución empírica y la hipótetica está calculada con el término cuadrático y el término $w(x)$ es un peso que se da esas diferencias.

Cuando $w(x)=1$ entonces se tiene la estadística de Cramér–von Mises; cuando $w(x)=[F_0(x)(1-F_0(x))]^{-1}$ entonces se tiene la estadística de Anderson–Darling, la cual por construcción asigna mayores pesos a observaciones en las colas de la distribución.

En R, la libreria "goftest" contiene las pruebas Anderson–Darling y Cramér–von Mises entre otras.

Retomando el ejemplo de las alturas de los pinos, probaremos ahora que las alturas tienen distribución normal y exponencial.

```{r}
X=Loblolly$height
meanx=mean(X)
meanx
sdx=sd(X)
sdx
library(goftest)
ad.test(X,null = "pnorm",mean=meanx,sd=sdx)
cvm.test(X,null = "pnorm",mean=meanx,sd=sdx)
ad.test(X,null = "pexp",rate=1/meanx)
cvm.test(X,null = "pexp",rate=1/meanx)

```

## Mas ejercicios

1. Cinco niños de cuarto grado de primaria fueron seleccionados al azar de todos los niños de ese grado en la escuela "15 de septiembre", para participar en una carrera. Sus tiempos en segundos fueron: 6.3, 4.2, 4.7, 6.0, y 5.7. Probar con  la hipótesis de que los tiempos provienen de una distribución uniforme en el intervalo de 4 a 8 segundos. 

2. La siguiente muestra aleatoria hace referencia a los rendimientos positivos de cierta acción a lo largo del tiempo. 


0.2513, 0.2566, 0.3459, 0.6379, 2.0505, 1.803, 2.1906,1.5299, 
0.35005, 0.3128, 1.2726, 2.3674, 2.3214, 2.4373, 0.6548. 


¿Usted piensa que la anterior muestra sigue una distribución normal?

Realizar la prueba correspondiente para verificar que su suposición es cierta con un nivel de confianza del $90\%$. 

3. Se obtuvieron sesenta y dos observaciones de un experimento, y se plantea la pregunta de si dichas observaciones provienen de una distribución normal con media 12 y desviación estándar 3. Ninguna observación se encontró por debajo del cuartil inferior de la distribución, 35 estuvieron por arriba de cuartil superior, 22 tomaron valores menores a la mediana, y 5 estuvieron entre la mediana y el cuartil superior. ¿Es posible concluir que las observaciones provienen de la distribución mencionada?
